### ISSUE TITLE
mainnet chain info

### ISSUE THREAD

**Issue by UsmannK** [babylonchain/babylon-relayer#45]
Hi, I noticed that babylon mainnet is live now (congrats!)

Where can I find info on the comsos config for the mainnet bbn chain?

Thanks!

**Comment by vitsalis** [comment]
The phase-1 mainnet that has launched only involves Bitcoin locking without a Babylon PoS chain operating. Thus, there's no mainnet cosmos config.

**Comment by UsmannK** [comment]
understood, thanks!
